{{- if and .Values.deployment.enabled (eq .Values.deployment.kind "Deployment") -}}
  {{- if gt (int .Values.deployment.replicas) 1 -}}
  {{- end -}}
  {{- if eq (default .Chart.AppVersion .Values.image.tag) "latest" }}
    {{- fail "\n\n ERROR: latest tag should not be used" }}
  {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-proxy.name" . }}
    helm.sh/chart: {{ include "redis-proxy.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.deployment.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.deployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ default 1 .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    {{ template "redis-proxy.podTemplate" . }}
{{- end -}}