deployment:
  enabled: true
  # Can be either Deployment or DaemonSet
  kind: Deployment
  # Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 1
  # Additional deployment labels (e.g. for filtering deployment by custom labels)
  labels: {
    app.kubernetes.io/app: redis-proxy
  }
  # Additional daemonset annotations
  annotations: { }
  # Additional pod annotations
  podAnnotations: { }

image:
  repository: aigis/socat
  tag: 1.7.4.4-r0
  pullPolicy: IfNotPresent

# Chart name override
nameOverride: ""

# Fully qualified app name override
fullnameOverride: ""

# Pod resources
resources: {}
  # requests:
  #   cpu: "50m"
  #   memory: "50Mi"
  # limits:
  #   cpu: "50m"
  #   memory: "100Mi"

source:
  address:
    type: TCP-LISTEN
    port: 6379
    options:
      - fork
      - reuseaddr

destination:
  address:
    type: OPENSSL
    host: myhost
    port: 6379
    options:

# Service session affinity
sessionAffinity: None # ClientIP


